site:
  title: Documentation
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://lisk.io/documentation
  start_page: lisk-sdk::index.adoc
asciidoc:
  attributes:
    plantuml-server-url: http://www.plantuml.com/plantuml
    toc: ~
    imagesdir: ~
  extensions:
#  - asciidoctor-emoji
  - asciidoctor-plantuml
#  - asciidoctor-chart
  - ./lib/tabs-block/extension.js
content:
  sources:
  - url: https://github.com/LiskHQ/lisk-docs.git
    branches: [docs-sdk, docs-core]
    #start_path: docs
ui:
  bundle:
    url: https://github.com/LiskHQ/lisk-docs/raw/dev-antora/build/ui-bundle.zip
#   url: ./antora/build/ui-bundle.zip
    snapshot: true
output:
  dir: ./master
