site:
  title: Lisk documentation
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://lisk.io/documentation
  start_page: lisk-sdk::index.adoc
asciidoc:
  attributes:
    plantuml-server-url: http://www.plantuml.com/plantuml
    toc: ~
    imagesdir: ~
    description: 'The Lisk Documentation comprises guides, tutorials, technical references and in-depth explanations about the Lisk SDK, Lisk Core, Lisk Service and the Lisk Protocol.@'
    idprefix: ''
    idseparator: '-'
  extensions:
#  - asciidoctor-emoji
#  - asciidoctor-plantuml
#  - asciidoctor-chart
  - ./lib/tabs-block/extension.js
content:
  sources:
  - url: https://github.com/LiskHQ/lisk-docs.git
    branches: [docs-service, 769-framework, docs-sdk-4.0.0, docs-sdk-3.0.2, docs-core-3.0.0-beta.0, docs-protocol, docs-sdk-2.3.8, docs-core-2.1.6, 754-releases]
    #start_path: docs
ui:
  bundle:
#    url: https://github.com/LiskHQ/lisk-docs/raw/dev-antora/build/ui-bundle.zip
   url: ./dev-antora/build/ui-bundle.zip
   snapshot: true
output:
  dir: ./development
