site:
  title: Docs
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://lisk.io/documentation
  start_page: lisk-sdk::index.adoc
asciidoc:
  attributes:
    plantuml-server-url: http://www.plantuml.com/plantuml
    toc: ~
    imagesdir: ~
    description: 'The Lisk Documentation comprises guides, tutorials, technical references and in-depth explanations about the Lisk SDK, Lisk Core and the Lisk Protocol.@'
  extensions:
#  - asciidoctor-emoji
  - asciidoctor-plantuml
#  - asciidoctor-chart
  - ./lib/tabs-block/extension.js
content:
  sources:
  - url: https://github.com/LiskHQ/lisk-docs.git
    branches: [453-dev-changelog-3.0, docs-core, docs-sdk-2.3.7, docs-core-2.1.5]
    #start_path: docs
ui:
  bundle:
#    url: https://github.com/LiskHQ/lisk-docs/raw/dev-antora/build/ui-bundle.zip
   url: ./dev-antora/build/ui-bundle.zip
   snapshot: true
output:
  dir: ./master
