site:
  title: Lisk documentation
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://lisk.io/documentation
  start_page: lisk-sdk::index.adoc
asciidoc:
  attributes:
    plantuml-server-url: http://www.plantuml.com/plantuml
    imagesdir: ~
    idprefix: ''
    idseparator: '-'
  extensions:
#  - asciidoctor-emoji
#  - asciidoctor-plantuml
#  - asciidoctor-chart
  - ./lib/tabs-block/extension.js
content:
  sources:
  - url: https://github.com/LiskHQ/lisk-docs.git
    branches: [1078-intro-updates, docs-service, docs-core, docs-sdk-4.0.0, docs-sdk-3.0.2, docs-sdk-2.3.8, docs-core-3.0.0-beta.1,  docs-core-2.1.6, docs-manual]
#    start_path: docs
ui:
  bundle:
#    url: https://github.com/LiskHQ/lisk-docs/raw/dev-antora/build/ui-bundle.zip
   url: ./dev-antora/build/ui-bundle.zip
   snapshot: true
output:
  dir: ./master
